sdf

diff --git a/dbx-using-cicdtools-azdevops/templates/dbrickscli.yml b/dbx-using-cicdtools-azdevops/templates/dbrickscli.yml
--- a/dbx-using-cicdtools-azdevops/templates/dbrickscli.yml
+++ b/dbx-using-cicdtools-azdevops/templates/dbrickscli.yml
@@ -37,12 +37,40 @@ jobs:
             pip install databricks-cli
           displayName: 'Install Databricks CLI'
 
-        - script: |
-            export DATABRICKS_HOST=${{ parameters.databricksHost }}
-            export DATABRICKS_CLIENT_ID=${{ parameters.databricksClientId }}
-            export DATABRICKS_CLIENT_SECRET=${{ parameters.databricksClientSecret }}
-            databricks workspace ls
-          displayName: 'Configure Databricks CLI with Client Credentials'
+
+        - task: PowerShell@2
+          displayName: "Configure Databricks CLI"
+          env:
+            DATABRICKS_HOST: ${{ parameters.databricksHost }}
+            DATABRICKS_CLIENT_ID: ${{ parameters.databricksClientId }}
+            DATABRICKS_CLIENT_SECRET: ${{ parameters.databricksClientSecret }}
+          inputs:
+            targetType: 'inline'
+            script: |
+              echo "Setting up Databricks CLI..."
+              $userProfile = [Environment]::GetFolderPath("UserProfile")
+              $configPath = Join-Path -Path $userProfile -ChildPath ".databricks-config"
+              Set-Content -Path $configPath -Value @"
+              [DEFAULT]
+              host = $env:DATABRICKS_HOST
+              token = $env:DATABRICKS_TOKEN
+              "@
+              
+              if (Test-Path $configPath) {
+                  Write-Host "Databricks CLI configuration file created successfully."
+                  $env:DATABRICKS_CONFIG_FILE = $configPath
+                  Write-Host "DATABRICKS_CONFIG_FILE environment variable set to $configPath"
+              } else {
+                  Write-Error "Failed to create Databricks CLI configuration file."
+                  exit 1
+              }
+
+        # - script: |
+        #     export DATABRICKS_HOST=${{ parameters.databricksHost }}
+        #     export DATABRICKS_CLIENT_ID=${{ parameters.databricksClientId }}
+        #     export DATABRICKS_CLIENT_SECRET=${{ parameters.databricksClientSecret }}
+        #     databricks workspace ls
+        #   displayName: 'Configure Databricks CLI with Client Credentials'
 
 
         # - task: AzureCLI@2
